#!/bin/sh

/usr/local/rrdtool/bin/rrdtool create wind.rrd \
	DS:WindSpeed:DERIVE:600:0:U      \
	RRA:AVERAGE:0.5:1:600      \
        RRA:AVERAGE:0.5:6:700      \
        RRA:AVERAGE:0.5:24:775     \
        RRA:AVERAGE:0.5:288:797    \
        RRA:MAX:0.5:1:600          \
        RRA:MAX:0.5:6:700          \
        RRA:MAX:0.5:24:775         \
        RRA:MAX:0.5:288:797
