#
# don't use special devices: "HM-CCU-1", "HM-RCV-50", "HMW-RCV-50"  !!!
#
CFG_THUMBDIR       /www/config/img/devices/50/
#
# baseid            thumbnail-image             description-name
#
WS550               9_hm-ws550-us_thumb         Wetterstation
HM-WDS100-C6-O      WeatherCombiSensor_thumb    Wetter Kombisensor
HM-WDS10-TH-O       TH_CS_thumb                 Wettersensor aussen
HM-WDS30-T-O        IP65_G201_thumb             Temperatursensor aussen
HM-WS550STH-I       13_hm-ws550sth-i_thumb      Temperatursensor innen
HM-Sen-Wa-Od        82_hm-sen-wa-od_thumb       Kapaz. F&uuml;llstandsmesser

HM-CC-TC            42_hm-cc-tc_thumb           Wandthermostat
HM-TC-IT-WM-W-EU    96_hm-tc-it-wm-w-eu_thumb   Wandthermostat (neu)
HM-CC-VD            43_hm-cc-vd_thumb           Ventilantrieb
HM-CC-RT-DN         83_hm-cc-rt-dn_thumb        Heizungsthermostat
HM-CC-VG-1          95_group_hm-cc-vg-1_thumb   Heizungsthermostat (Gruppe)

HM-Sec-SC           16_hm-sec-sc_thumb          T&uuml;rsensor
HM-Sec-RHS          17_hm-sec-rhs_thumb         Fenster-/ Drehgriffkontakt
HM-Sen-EP           48_hm-sen-ep_thumb          Impulssensor
HM-Sec-WDS          49_hm-sec-wds_thumb         Wassermelder
HM-Sen-RD-O         87_hm-sen-rd-o_thumb        Regensensor

HM-PB-2-WM          PushButton-2ch-wm_thumb     Wandtaster 2 Kanal
HM-PB-4-WM          PushButton-4ch-wm_thumb     Wandtaster 4 Kanal
HM-PB-6-WM55        86_hm-pb-6-wm55_thumb       Wandtaster 6 Kanal
HM-RC-P1            21_hm-rc-p1_thumb           Handsender 1 Taste
HM-RC-4             18_hm-rc-4_thumb            Handsender 4 Tasten
HM-RC-12            19_hm-rc-12_thumb           Fernbedienung 12 Tasten
HM-RC-19            20_hm-rc-19_thumb           Fernbedienung 19 Tasten

HM-Sec-MDIR         50_hm-sec-mdir_thumb        Innen-Bewegungsmelder
HM-Sen-MDIR-SM      53_hm-sen-mdir-sm_thumb     Bewegungsmelder
HM-Sen-MDIR-O       80_hm-sen-mdir-o_thumb      Aussen-Bewegungsmelder

HM-LC-Sw1-FM        4_hm-lc-sw1-fm_thumb        Schaltaktor 1fach Unterputz
HM-LC-Sw2-FM        5_hm-lc-sw2-fm_thumb        Schaltaktor 2fach Unterputz
HM-LC-Sw1-SM        8_hm-lc-sw1-sm_thumb        Schaltaktor 1fach Aufputz
HM-LC-Sw4-SM        3_hm-lc-sw4-sm_thumb        Schaltaktor 4fach Aufputz
HM-LC-Sw2-DR        69_hm-lc-sw2-dr_thumb       Schaltaktor 2fach Hutschiene
HM-LC-Sw4-DR        68_hm-lc-sw4-dr_thumb       Schaltaktor 4fach Hutschiene
HM-LC-Sw1-Ba-PCB    77_hm-lc-sw1-ba-pcb_thumb   Schaltaktor 1fach Platine
HM-LC-Sw4-PCB       46_hm-lc-sw4-pcb_thumb      Schaltaktor 4fach Platine
HM-LC-Sw1-Pl        OM55_DimmerSwitch_thumb     Zwischenstecker Schalter
HM-LC-Sw1PBU-FM     PushButton-2ch-wm_thumb     Schaltaktor 1-fach Schalter
HM-ES-PMSw1-Pl      93_hm-es-pmsw1-pl_thumb     Schaltaktor mit Leistungsmessung

HM-LC-Bl1-FM        7_hm-lc-bl1-fm_thumb        Jalousieaktor 1fach Unterputz
HM-LC-Bl1-SM        6_hm-lc-bl1-sm_thumb        Jalousieaktor 1fach Aufputz
HM-LC-Bl1PBU-FM     PushButton-2ch-wm_thumb     Jalousieaktor 1fach Schalter
HM-LC-Ja1PBU-FM     PushButton-2ch-wm_thumb     Jalousieaktor mit Lamellen

HM-LC-Dim1T-FM      65_hm-lc-dim1t-fm_thumb     Dimmaktor 1fach Unterputz
HM-LC-Dim2L-SM      45_hm-lc-dim2l-sm_thumb     Dimmaktor 2fach Aufputz
HM-LC-Dim1L-CV      2_hm-lc-dim1l-cv_thumb      Zwischendecken Dimmer
HM-LC-Dim1L-Pl      OM55_DimmerSwitch_thumb     Zwischenstecker Dimmer
HM-LC-Dim1TPBU-FM   PushButton-2ch-wm_thumb     Dimmaktor 1fach Schalter

HM-OU-CF-Pl         60_hm-ou-cf-pl_thumb        Signalgeber/Gong
HM-EM-CMM           25_hm-em-cmm_thumb          Z&auml;hlersensor Management
HM-EM-CCM           44_hm-em-ccm_thumb          Z&auml;hlersensor Kamera
HM-OU-LED16         78_hm-ou-led16_thumb        Statusanzeige 16 Kanal
HM-Sec-SD           51_hm-sec-sd_thumb          Rauchmelder
HM-Sec-SD-Team      52_hm-sec-sd-team_thumb     Rauchmelder (Gruppe)
HM-Sec-Key          14_hm-sec-key_thumb         KeyMatic

