#!/bin/sh

/usr/local/rrdtool/bin/rrdtool create sensor.rrd \
	DS:Temperature:GAUGE:600:U:U      \
	RRA:AVERAGE:0.5:1:600      \
        RRA:AVERAGE:0.5:6:700      \
        RRA:AVERAGE:0.5:24:775     \
        RRA:AVERAGE:0.5:288:797    \
        RRA:MAX:0.5:1:600          \
        RRA:MAX:0.5:6:700          \
        RRA:MAX:0.5:24:775         \
        RRA:MAX:0.5:288:797	\
        RRA:MIN:0.5:1:600          \
        RRA:MIN:0.5:6:700          \
        RRA:MIN:0.5:24:775         \
        RRA:MIN:0.5:288:797
