#!/bin/sh

ADDON_DIR=/usr/local/addons/cuxd
RCD_DIR=/usr/local/etc/config/rc.d
CONFIG_DIR=/usr/local/etc/config

# mount /usr/local if not already mounted
mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

# make sure the addon and rc.d dir exist
mkdir -p $ADDON_DIR
chmod 755 $ADDON_DIR
mkdir -p $RCD_DIR
chmod 755 $RCD_DIR

# remove old stuff
rm -f $ADDON_DIR/fw.tar.gz
rm -f $ADDON_DIR/*.ko
rm -f $ADDON_DIR/lib*.so*
rm -f $ADDON_DIR/*.ccc
rm -f $ADDON_DIR/hm_addons.cfg.*
rm -f $ADDON_DIR/cuxd_addon.cfg
rm -f $ADDON_DIR/extra/curl

# remove daemon
rm -f $ADDON_DIR/cuxd

# remove link to website
rm -f $CONFIG_DIR/addons/www/cuxd

# save current configuration
cp -af $ADDON_DIR/cuxd.ps $ADDON_DIR/cuxd.ps.old

# copy addon
cp -R cuxd/* $ADDON_DIR/

# copy startup script
cp rc.d/cuxdaemon $RCD_DIR/
chmod +x $RCD_DIR/cuxdaemon

# link to website
ln -sf $ADDON_DIR $CONFIG_DIR/addons/www/cuxd

# add menu
touch /usr/local/etc/config/hm_addons.cfg
$ADDON_DIR/update_addon cuxd $ADDON_DIR/cuxd_addon.cfg

# sync filesystem to make sure all changes are written to disk
sync

# all CCUs perform a reboot after installing
# addons via WebUI.
exit 0
